fix(api): Fix SupportedVerifierTypes import (#207)
I was getting errors like these:
```
 FAIL   api  src/directives/requireAuth/requireAuth.test.ts [ api/src/directives/requireAuth/requireAuth.test.ts ]
SyntaxError: The requested module '../auth/verifiers/index.js' does not provide an export named 'SupportedVerifierTypes'
 ❯ src/directives/requireAuth/requireAuth.test.ts:1:1
      1| import { mockRedwoodDirective, getDirectiveName } from '@cedarjs/testing/api'
       | ^
      2|
      3| import requireAuth from './requireAuth.js'
```

This PR should fix that by making sure `SupportedVerifyerTypes` is
properly imported from the correct location